### ISSUE TITLE
Styles

### ISSUE THREAD

**Issue by trofort** [christinakulik/NOTEme#1]
Добавь это в стили для Вью, ибо часто используется

https://github.com/christinakulik/NOTEme/blob/ec53123641f8f245c5f87e0e58c0bf6f7b790c75/NOTEme/Modules/Auth/RegisterVC.swift#L13-L17

**Comment by christinakulik** [comment]
Done 
https://github.com/christinakulik/NOTEme/blob/691cf3cae868db0089a8ca98864250776f2674e8/NOTEme/Modules/Auth/LoginVC.swift#L13
